### ISSUE TITLE
Can I ru  this swift code in not iPad but Xcode?

### ISSUE THREAD

**Issue by bemoregt** [kkk669/coreml-playground#1]
HI, @kkk669 

Can I ru  this swift code in not iPad but Xcode (MacOSX)?

please, tell me.

Thanks.

from @bemoregt.

**Comment by kkebo** [comment]
@bemoregt I’m sorry but I cannot test it on Xcode right away because my laptop was broken recently. However, I believe you can run this playground on Xcode except the “Camera Detection” page because it requires iOS device’s camera.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kkebo** [comment]
I decided not to support for Xcode to optimize more for Swift Playgrounds, but feel free to use my code in your Xcode.
